### ISSUE TITLE
[Votaçao] Injeção de dependecia?

### ISSUE THREAD

**Issue by felipebaltazar** [XamarinTrio/Xamarin.Community.BR#1]
## Votação

Na documentação da microsoft, [de padrões de empresarial](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/enterprise-application-patterns/dependency-injection), temos a sugestão para utilizar o [TinyIoc](https://github.com/grumpydev/TinyIoC/wiki) para injeção de dependencia.
Podemos seguir esse conceito se todos concordarem.

**Comment by MarcosAC** [comment]
Pra mim ta bão. Estarei aprendendo um trem novo.
